version: '2'

networks:
  kafka-net:
    driver: bridge

services:
  zookeeper-server:
    image: 'bitnami/zookeeper:latest'
    networks:
      - kafka-net
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka-server1:
    image: 'bitnami/kafka:latest'
    networks:
      - kafka-net
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-server
#  kafka-server2:
#    image: 'bitnami/kafka:latest'
#    networks:
#      - kafka-net
#    ports:
#      - '9093:9093'
#    environment:
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
#      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9093
#      - ALLOW_PLAINTEXT_LISTENER=yes
#    depends_on:
#      - zookeeper-server
  mysql:
    # *-----------------------------*
    # To connect to the DB:
    #   docker-compose exec mysql bash -c 'mysql -uroot -p$MYSQL_ROOT_PASSWORD'
    # *-----------------------------*
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Admin123
      MYSQL_USER: connect_user
      MYSQL_PASSWORD: asgard
    security_opt:
     - seccomp:unconfined
    cap_add:
     - SYS_NICE  # CAP_SYS_NICE
    volumes:
     - ./resources/docker-sql:/docker-entrypoint-initdb.d/
     - ./target/data/mysql:/var/lib/mysql:rw
